//! # extobj
//!
//! A tiny, zero-cost library that lets you **extend a struct with new fields
//! across crate boundaries** without recompiling upstream crates.
//!
//! ## Quick start
//!
//! ```
//! use extobj::{extobj, ExtObj};
//!
//! // 1. Declare the extension object type.
//! extobj!(pub struct Player);
//!
//! // 2. In any downstream crate add fields.
//! extobj!(impl Player {
//!     pub health: i32,
//!     pub level:  u32,
//! });
//!
//! // 3. Use it.
//! let mut p = ExtObj::<Player>::new();
//! p[*health] = 100;
//! p[*level]  = 5;
//! assert_eq!(p[*health], 100);
//! ```
//!
//!
//! ## How it works
//!
//! Every field becomes a `static Var<Player, T>` singleton holding the byte
//! offset of that field.  Fields are registered at load time (via `ctor`), and
//! the first `ExtObj::<Player>::new()` freezes the layout.  From then on every
//! `ExtObj<Player>` is a **single heap allocation** with all fields stored
//! inline, so field access is a plain `base + offset`.  Construction /
//! destruction are routed through an internal v-table generated by the macro.
//! All public APIs are safe; the unsafe internals are confined to the crate.
//!
//! Field types must be `Default + Send + Sync + 'static`; this is what makes
//! `ExtObj<O>` itself `Send + Sync`.
//!
//! Registering a new field *after* the layout has been frozen panics.
//!
//! ## Optional crate rename
//!
//! ```
//! extobj::extobj!(struct Foo, crate_path = extobj);
//! extobj::extobj!(impl Foo { M: u8 }, crate_path = extobj);
//! ```
//!
//! ## Optional init code
//!
//! ```
//! extobj::extobj!(struct Foo);
//! extobj::extobj!(impl Foo { M: u8 }, init = register_deps());
//!
//! fn register_deps() {
//!     // do some init code here.
//! }
//! ```
//!
//! ## Cargo features
//!
//! None – only depends on `std`.

#![warn(missing_docs)]
#![allow(non_camel_case_types)] // used by the macro-generated marker types

mod dynobj;

pub use ctor;
pub use dynobj::DynObj;
pub use extobj_macro::extobj;
use parking_lot::Mutex;
pub use parking_lot::RwLock;
use std::{
    alloc::{Layout, alloc, dealloc, handle_alloc_error},
    fmt::{self, Debug, Formatter},
    hash::{Hash, Hasher},
    marker::PhantomData,
    mem::{self, align_of, needs_drop, size_of},
    ops::{Index, IndexMut},
    ptr::{self, NonNull},
    sync::OnceLock,
};

#[derive(Clone, Copy)]
struct Field {
    offset: usize,
    init: unsafe fn(*mut u8),
    /// `None` when `T` has no drop glue, so the indirect call is skipped.
    drop: Option<unsafe fn(*mut u8)>,
}

struct Pending {
    size: usize,
    align: usize,
    fields: Vec<Field>,
}

struct Frozen {
    layout: Layout,
    fields: Box<[Field]>,
}

/// Per-`O` field registry.  Fields are appended while `frozen` is unset; the
/// first `ExtObj::new` freezes the layout so the hot path only needs a single
/// acquire load.
#[doc(hidden)]
pub struct Defs {
    pending: Mutex<Pending>,
    frozen: OnceLock<Frozen>,
}

impl Defs {
    #[doc(hidden)]
    pub const fn new() -> Self {
        Self {
            pending: Mutex::new(Pending {
                size: 0,
                align: 1,
                fields: Vec::new(),
            }),
            frozen: OnceLock::new(),
        }
    }

    #[inline]
    fn frozen(&self) -> &Frozen {
        self.frozen.get_or_init(|| {
            let mut p = self.pending.lock();
            Frozen {
                layout: Layout::from_size_align(p.size, p.align)
                    .expect("extobj: field layout overflow")
                    .pad_to_align(),
                fields: mem::take(&mut p.fields).into_boxed_slice(),
            }
        })
    }
}

/// # Note
/// This trait is for used only in macros.
#[doc(hidden)]
pub trait __ExtObjDef: 'static {
    fn defs() -> &'static Defs;
}

/// An extendable struct that be extented across crate.
pub struct ExtObj<O: __ExtObjDef>(NonNull<u8>, PhantomData<O>);

// SAFETY: `Var::__new` is the only way to register a field and requires
// `T: Send + Sync`, so every value stored in the block is `Send + Sync`.
unsafe impl<O: __ExtObjDef> Send for ExtObj<O> {}
unsafe impl<O: __ExtObjDef> Sync for ExtObj<O> {}

impl<O: __ExtObjDef> ExtObj<O> {
    /// Creates a new, empty `ExtObj` with every registered field initialized to its
    /// default value.
    pub fn new() -> Self {
        let frozen = O::defs().frozen();
        let layout = frozen.layout;

        let base = if layout.size() == 0 {
            ptr::without_provenance_mut(layout.align())
        } else {
            let p = unsafe { alloc(layout) };
            if p.is_null() {
                handle_alloc_error(layout);
            }
            p
        };

        // Drops already-initialised fields and frees the block if an
        // initialiser panics.
        struct Guard<'a> {
            base: *mut u8,
            frozen: &'a Frozen,
            done: usize,
        }

        impl Drop for Guard<'_> {
            fn drop(&mut self) {
                unsafe {
                    drop_fields(self.base, &self.frozen.fields[..self.done]);
                    free(self.base, self.frozen.layout);
                }
            }
        }

        let mut guard = Guard {
            base,
            frozen,
            done: 0,
        };

        for (i, f) in frozen.fields.iter().enumerate() {
            unsafe { (f.init)(base.add(f.offset)) };
            guard.done = i + 1;
        }

        mem::forget(guard);

        Self(unsafe { NonNull::new_unchecked(base) }, PhantomData)
    }

    /// Immutably borrows the value of the given variable.
    #[inline]
    pub fn get<T>(&self, var: Var<O, T>) -> &T {
        unsafe { &*self.0.as_ptr().add(var.0).cast::<T>() }
    }

    /// Mutably borrows the value of the given variable.
    #[inline]
    pub fn get_mut<T>(&mut self, var: Var<O, T>) -> &mut T {
        unsafe { &mut *self.0.as_ptr().add(var.0).cast::<T>() }
    }
}

#[inline]
unsafe fn drop_fields(base: *mut u8, fields: &[Field]) {
    for f in fields {
        if let Some(drop) = f.drop {
            unsafe { drop(base.add(f.offset)) };
        }
    }
}

#[inline]
unsafe fn free(base: *mut u8, layout: Layout) {
    if layout.size() != 0 {
        unsafe { dealloc(base, layout) };
    }
}

impl<O: __ExtObjDef> Default for ExtObj<O> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

impl<O: __ExtObjDef> Drop for ExtObj<O> {
    fn drop(&mut self) {
        // `new` already froze the layout, so this is a single acquire load.
        let frozen = O::defs().frozen();
        let base = self.0.as_ptr();

        unsafe {
            drop_fields(base, &frozen.fields);
            free(base, frozen.layout);
        }
    }
}

impl<O: __ExtObjDef, T> Index<Var<O, T>> for ExtObj<O> {
    type Output = T;

    #[inline]
    fn index(&self, index: Var<O, T>) -> &Self::Output {
        self.get(index)
    }
}

impl<O: __ExtObjDef, T> IndexMut<Var<O, T>> for ExtObj<O> {
    #[inline]
    fn index_mut(&mut self, index: Var<O, T>) -> &mut Self::Output {
        self.get_mut(index)
    }
}

/// A typed handle to one field in an `ExtObj<O>`.
///
/// Values of this type are produced by the `extobj!` macro and are normally
/// used as `static` items.
#[repr(transparent)]
pub struct Var<O, T>(usize, PhantomData<(O, T)>);

impl<O, T> Var<O, T> {
    /// Erase the type of the variable and extract the information representing this
    /// variable in the extobj type.
    #[inline]
    pub fn var_id(self) -> VarId<O> {
        VarId(self.0, PhantomData)
    }
}

impl<O, T> Clone for Var<O, T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}

impl<O, T> Copy for Var<O, T> {}

impl<O, T> Debug for Var<O, T> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Var").field(&self.0).finish()
    }
}

impl<O, T> Eq for Var<O, T> {}

impl<O, T> Hash for Var<O, T> {
    #[inline]
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl<O, T> PartialEq for Var<O, T> {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<O: __ExtObjDef, T: Default + Send + Sync + 'static> Var<O, T> {
    #[doc(hidden)]
    pub fn __new() -> Self {
        let defs = O::defs();
        let mut p = defs.pending.lock();

        // Checked under the lock: `frozen()` also takes it, so a field is
        // either fully included in the layout or rejected here.
        assert!(
            defs.frozen.get().is_none(),
            "extobj: cannot register field `{}` on `{}` after an ExtObj of that type was created",
            std::any::type_name::<T>(),
            std::any::type_name::<O>(),
        );

        let align = align_of::<T>();
        let offset = (p.size + align - 1) & !(align - 1);

        p.size = offset + size_of::<T>();
        p.align = p.align.max(align);
        p.fields.push(Field {
            offset,
            init: init_default::<T>,
            drop: needs_drop::<T>().then_some(drop_in_place::<T> as unsafe fn(*mut u8)),
        });

        Self(offset, PhantomData)
    }
}

unsafe fn init_default<T: Default>(ptr: *mut u8) {
    unsafe { ptr.cast::<T>().write(T::default()) }
}

unsafe fn drop_in_place<T>(ptr: *mut u8) {
    unsafe { ptr::drop_in_place(ptr.cast::<T>()) }
}

/// The variable identifier inside the extobj. This can be hashed.
pub struct VarId<O>(usize, PhantomData<O>);

impl<O> Clone for VarId<O> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}

impl<O> Copy for VarId<O> {}

impl<O> Debug for VarId<O> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.debug_tuple("VarId").field(&self.0).finish()
    }
}

impl<O> Eq for VarId<O> {}

impl<O> Hash for VarId<O> {
    #[inline]
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl<O> PartialEq for VarId<O> {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<O, T> PartialEq<Var<O, T>> for VarId<O> {
    #[inline]
    fn eq(&self, other: &Var<O, T>) -> bool {
        self.0 == other.0
    }
}

impl<O, T> PartialEq<VarId<O>> for Var<O, T> {
    #[inline]
    fn eq(&self, other: &VarId<O>) -> bool {
        self.0 == other.0
    }
}
